//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class osu2008Entities1 : DbContext
    {
        public osu2008Entities1()
            : base("name=osu2008Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumniAddressSet> AlumniAddressSet { get; set; }
        public virtual DbSet<ClassYearSet> ClassYearSet { get; set; }
        public virtual DbSet<EventSet> EventSet { get; set; }
        public virtual DbSet<EventSet_Activity> EventSet_Activity { get; set; }
        public virtual DbSet<EventSet_Information> EventSet_Information { get; set; }
        public virtual DbSet<OccupationSet> OccupationSet { get; set; }
        public virtual DbSet<ProgramSet> ProgramSet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
        public virtual DbSet<UserSet_Alumni> UserSet_Alumni { get; set; }
        public virtual DbSet<UserSet_Employee> UserSet_Employee { get; set; }
    }
}
