//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSet_Alumni
    {
        public string Credits { get; set; }
        public string HasDegree { get; set; }
        public int OccupationOccupationId { get; set; }
        public int AlumniAddressAlumniAddressId { get; set; }
        public string ClassYearClassYearId { get; set; }
        public string UserId { get; set; }
    
        public virtual AlumniAddressSet AlumniAddressSet { get; set; }
        public virtual ClassYearSet ClassYearSet { get; set; }
        public virtual OccupationSet OccupationSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
